(() => {
  "use strict";
  const SUPABASE_URL = "https://nmtdliqubfpextwdfqkf.supabase.co";
  const KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5tdGRsaXF1YmZwZXh0d2RmcWtmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3OTExNzE0MjUsImV4cCI6MjEwNjc0NzQyNX0.9XrmjJ9usGauKu82L82DyL5dAt_YhfwZXq5uq55I2NY";
  const REST = `${SUPABASE_URL}/rest/v1`;
  const headers = { apikey: KEY, Authorization: `Bearer ${KEY}` };
  const $ = selector => document.querySelector(selector);
  const state = { lang: localStorage.getItem("len-lang") || "ar", products: [], categories: [], settings: {}, category: "all", query: "", cart: JSON.parse(localStorage.getItem("len-cart") || "[]") };
  const dictionary = {
    ar:{announcement:"شحن لجميع المحافظات · اختاري جمالك مع LEN",home:"الرئيسية",shop:"المتجر",story:"قصتنا",contact:"تواصلي معنا",heroEyebrow:"جمالك، بطريقتك",heroTitle:"لمسة تُشبهكِ",heroText:"منتجات مختارة بعناية لتمنح بشرتكِ عناية رقيقة ومكياجًا يعبّر عنكِ.",shopNow:"تسوّقي الآن",carefullyChosen:"مختارة بعناية",carefullyChosenText:"منتجات نحبها ونثق بها",madeForYou:"صُنعت لأجلكِ",madeForYouText:"تجربة جمال رقيقة وبسيطة",fastDelivery:"توصيل سريع",fastDeliveryText:"لباب بيتك في كل المحافظات",collection:"مجموعة LEN",discover:"اكتشفي مفضلاتك",searchPlaceholder:"ابحثي عن منتج...",loading:"جارٍ تحميل المنتجات...",ourStory:"قصتنا",storyTitle:"لأن الجمال شعور قبل أن يكون مظهرًا",storyText:"بدأت LEN بحب التفاصيل الأنثوية الصغيرة. نختار كل منتج ليضيف لحظتكِ الخاصة من الثقة والدلال.",exploreCollection:"اكتشفي المجموعة ←",footerText:"جمالكِ الطبيعي هو مصدر إلهامنا.",quickLinks:"روابط سريعة",customerCare:"خدمة العملاء",supportHours:"يوميًا من 10 صباحًا إلى 10 مساءً",followUs:"تابعينا",rights:"جميع الحقوق محفوظة.",yourCart:"سلة مشترياتك",all:"الكل",add:"أضيفي للسلة",soldOut:"نفد المخزون",new:"جديد",empty:"لا توجد منتجات مطابقة.",cartEmpty:"سلة مشترياتك فارغة.",subtotal:"الإجمالي",checkout:"إتمام الطلب",remove:"حذف",inStock:"متوفر",quantity:"الكمية",checkoutTitle:"بيانات التوصيل",fullName:"الاسم بالكامل",phone:"رقم الهاتف",secondPhone:"رقم إضافي (اختياري)",governorate:"المحافظة",address:"العنوان بالتفصيل",notes:"ملاحظات (اختياري)",payment:"طريقة الدفع",instapay:"InstaPay",vodafone:"Vodafone Cash",deposit:"العربون المطلوب",placeOrder:"تأكيد الطلب",required:"يرجى إكمال جميع البيانات المطلوبة.",added:"تمت إضافة المنتج للسلة",orderSuccess:"تم استلام طلبك بنجاح",orderNumber:"رقم الطلب",orderError:"تعذر إرسال الطلب الآن. حاولي مرة أخرى.",details:"التفاصيل"},
    en:{announcement:"Delivery across Egypt · Find your beauty with LEN",home:"Home",shop:"Shop",story:"Our story",contact:"Contact",heroEyebrow:"Beauty, your way",heroTitle:"A touch that feels like you",heroText:"Carefully chosen skincare and makeup that celebrates your own expression.",shopNow:"Shop now",carefullyChosen:"Carefully chosen",carefullyChosenText:"Products we love and trust",madeForYou:"Made for you",madeForYouText:"A gentle, effortless beauty ritual",fastDelivery:"Fast delivery",fastDeliveryText:"Straight to your door across Egypt",collection:"The LEN collection",discover:"Discover your favorites",searchPlaceholder:"Search products...",loading:"Loading products...",ourStory:"Our story",storyTitle:"Beauty is a feeling before it is a look",storyText:"LEN began with a love for feminine details. Every product is selected to bring confidence and delight to your day.",exploreCollection:"Explore the collection →",footerText:"Your natural beauty inspires us.",quickLinks:"Quick links",customerCare:"Customer care",supportHours:"Daily, 10 AM to 10 PM",followUs:"Follow us",rights:"All rights reserved.",yourCart:"Your cart",all:"All",add:"Add to cart",soldOut:"Sold out",new:"New",empty:"No matching products.",cartEmpty:"Your cart is empty.",subtotal:"Subtotal",checkout:"Checkout",remove:"Remove",inStock:"In stock",quantity:"Quantity",checkoutTitle:"Delivery details",fullName:"Full name",phone:"Phone number",secondPhone:"Second phone (optional)",governorate:"Governorate",address:"Full address",notes:"Notes (optional)",payment:"Payment method",instapay:"InstaPay",vodafone:"Vodafone Cash",deposit:"Required deposit",placeOrder:"Place order",required:"Please complete all required information.",added:"Product added to cart",orderSuccess:"Your order has been received",orderNumber:"Order number",orderError:"We could not send your order. Please try again.",details:"Details"}
  };
  const t = key => dictionary[state.lang][key] || key;
  const esc = value => String(value ?? "").replace(/[&<>"']/g, c => ({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"})[c]);
  const productName = p => state.lang === "ar" ? (p.name_ar || p.name_en) : (p.name_en || p.name_ar);
  const description = p => state.lang === "ar" ? (p.description_ar || p.description_en || "") : (p.description_en || p.description_ar || "");
  const categoryName = c => state.lang === "ar" ? (c.name_ar || c.name_en) : (c.name_en || c.name_ar);
  const image = p => p.image_url || p.images?.[0]?.image_url || "";
  const money = value => `${Number(value || 0).toLocaleString(state.lang === "ar" ? "ar-EG" : "en-EG", {minimumFractionDigits:2,maximumFractionDigits:2})} ${state.settings.currency || "EGP"}`;
  const toast = message => { const node=$("#toast"); node.textContent=message; node.classList.add("show"); clearTimeout(toast.timer); toast.timer=setTimeout(()=>node.classList.remove("show"),2600); };
  async function get(path){ const response=await fetch(`${REST}${path}`,{headers}); const body=await response.json(); if(!response.ok) throw new Error(body.message || "Request failed"); return body; }
  async function load(){ try{ const [categories,products,settings]=await Promise.all([get("/categories?select=*&order=name_en"),get("/products?select=*,category:categories(*),images:product_images(*)&is_active=eq.true&order=created_at.desc"),get("/store_settings?select=*&limit=1")]); state.categories=categories; state.products=products; state.settings=settings[0]||{}; renderCategories(); renderProducts(); renderCart(); }catch(error){ console.error(error); $("#productGrid").innerHTML=`<div class="empty">${t("orderError")}</div>`; } }
  function applyLanguage(){ const isAr=state.lang==="ar"; document.documentElement.lang=state.lang; document.documentElement.dir=isAr?"rtl":"ltr"; document.body.dir=isAr?"rtl":"ltr"; $("#languageButton").textContent=isAr?"EN":"عربي"; document.querySelectorAll("[data-i18n]").forEach(node=>node.textContent=t(node.dataset.i18n)); document.querySelectorAll("[data-i18n-placeholder]").forEach(node=>node.placeholder=t(node.dataset.i18nPlaceholder)); renderCategories(); renderProducts(); renderCart(); }
  function renderCategories(){ const holder=$("#categoryTabs"); if(!holder)return; holder.innerHTML=`<button class="${state.category==="all"?"active":""}" data-category="all">${t("all")}</button>`+state.categories.map(c=>`<button class="${state.category===String(c.id)?"active":""}" data-category="${esc(c.id)}">${esc(categoryName(c))}</button>`).join(""); }
  function renderProducts(){ const holder=$("#productGrid"); if(!holder)return; const q=state.query.trim().toLowerCase(); const items=state.products.filter(p=>(state.category==="all"||String(p.category_id)===state.category)&&(!q||`${p.name_ar||""} ${p.name_en||""}`.toLowerCase().includes(q))); holder.innerHTML=items.length?items.map(p=>`<article class="product-card"><div class="product-media" data-product="${esc(p.id)}">${image(p)?`<img src="${esc(image(p))}" alt="${esc(productName(p))}" loading="lazy">`:`<div class="product-placeholder">Len</div>`}<span class="badge">${Number(p.stock_quantity)>0?t("new"):t("soldOut")}</span>${Number(p.stock_quantity)>0?`<button class="quick-add" data-add="${esc(p.id)}">${t("add")}</button>`:""}</div><div class="product-info"><small>${esc(categoryName(p.category||{}))}</small><h3>${esc(productName(p))}</h3><span class="price">${money(p.price)}</span></div></article>`).join(""):`<div class="empty">${t("empty")}</div>`; }
  function saveCart(){ localStorage.setItem("len-cart",JSON.stringify(state.cart)); renderCart(); }
  function addToCart(id){ const p=state.products.find(item=>String(item.id)===String(id)); if(!p||Number(p.stock_quantity)<=0)return; const row=state.cart.find(item=>String(item.id)===String(id)); if(row)row.quantity=Math.min(row.quantity+1,Number(p.stock_quantity)); else state.cart.push({id:p.id,quantity:1}); saveCart(); toast(t("added")); }
  function cartProducts(){ return state.cart.map(row=>({row,product:state.products.find(p=>String(p.id)===String(row.id))})).filter(x=>x.product); }
  function cartTotal(){ return cartProducts().reduce((sum,x)=>sum+Number(x.product.price)*x.row.quantity,0); }
  function renderCart(){ const items=cartProducts(); $("#cartCount").textContent=state.cart.reduce((sum,item)=>sum+item.quantity,0); $("#cartItems").innerHTML=items.length?items.map(({row,product})=>`<div class="cart-row">${image(product)?`<img src="${esc(image(product))}" alt="">`:`<div class="mini-placeholder">LEN</div>`}<div><h4>${esc(productName(product))}</h4><span class="price">${money(product.price)}</span><div class="quantity"><button data-qty="${esc(product.id)}" data-delta="-1">−</button><span>${row.quantity}</span><button data-qty="${esc(product.id)}" data-delta="1">+</button></div></div><button class="remove" data-remove="${esc(product.id)}">×</button></div>`).join(""):`<div class="empty">${t("cartEmpty")}</div>`; $("#cartSummary").innerHTML=items.length?`<div class="summary-line"><b>${t("subtotal")}</b><b class="price">${money(cartTotal())}</b></div><button class="checkout-button" id="checkoutButton">${t("checkout")}</button>`:""; }
  function openCart(open=true){ $("#cartDrawer").classList.toggle("open",open); $("#backdrop").classList.toggle("open",open); document.body.style.overflow=open?"hidden":""; }
  function showProduct(id){ const p=state.products.find(item=>String(item.id)===String(id)); if(!p)return; $("#productDetails").innerHTML=`<div class="dialog-product">${image(p)?`<img src="${esc(image(p))}" alt="${esc(productName(p))}">`:`<div class="detail-placeholder">Len</div>`}<div class="dialog-copy"><p class="eyebrow">${esc(categoryName(p.category||{}))}</p><h2>${esc(productName(p))}</h2><p class="price">${money(p.price)}</p><p class="description">${esc(description(p))}</p><p class="stock">${Number(p.stock_quantity)>0?`${t("inStock")} · ${p.stock_quantity}`:t("soldOut")}</p>${Number(p.stock_quantity)>0?`<button class="primary-button" data-add="${esc(p.id)}">${t("add")}</button>`:""}</div></div>`; $("#productDialog").showModal(); }
  function checkout(){ const depositPct=Number(state.settings.deposit_percentage??30); const deposit=cartTotal()*depositPct/100; $("#checkoutContent").innerHTML=`<div class="checkout-wrap"><p class="eyebrow">LEN</p><h2>${t("checkoutTitle")}</h2><form class="checkout-form" id="checkoutForm"><div class="field"><label>${t("fullName")}</label><input name="full_name" required></div><div class="field"><label>${t("phone")}</label><input name="phone" inputmode="tel" required></div><div class="field"><label>${t("secondPhone")}</label><input name="second_phone" inputmode="tel"></div><div class="field"><label>${t("governorate")}</label><input name="governorate" required></div><div class="field full"><label>${t("address")}</label><textarea name="address" rows="3" required></textarea></div><div class="field full"><label>${t("notes")}</label><textarea name="notes" rows="2"></textarea></div><div class="field"><label>${t("payment")}</label><select name="payment_method"><option value="instapay">${t("instapay")}</option><option value="vodafone_cash">${t("vodafone")}</option></select></div><div class="order-total"><div class="summary-line"><span>${t("subtotal")}</span><b class="price">${money(cartTotal())}</b></div><div class="summary-line"><span>${t("deposit")} (${depositPct}%)</span><b class="price">${money(deposit)}</b></div></div><button class="checkout-button field full" type="submit">${t("placeOrder")}</button></form></div>`; openCart(false); $("#checkoutDialog").showModal(); }
  async function submitOrder(form){ const button=form.querySelector("button[type=submit]"); button.disabled=true; const data=Object.fromEntries(new FormData(form)); const total=cartTotal(), depositPct=Number(state.settings.deposit_percentage??30), orderNumber=`LEN-${Date.now().toString().slice(-8)}`; const items=cartProducts().map(({row,product})=>({product_id:product.id,product_name_ar:product.name_ar,product_name_en:product.name_en,quantity:row.quantity,unit_price:Number(product.price),total_price:Number(product.price)*row.quantity})); try{ const customerResponse=await fetch(`${REST}/customers`,{method:"POST",headers:{...headers,"Content-Type":"application/json",Prefer:"return=representation"},body:JSON.stringify({full_name:data.full_name,phone:data.phone,second_phone:data.second_phone||null,governorate:data.governorate,address:data.address,notes:data.notes||null})}); const customers=await customerResponse.json(); if(!customerResponse.ok)throw new Error(customers.message); const customer=Array.isArray(customers)?customers[0]:customers; const orderResponse=await fetch(`${REST}/orders`,{method:"POST",headers:{...headers,"Content-Type":"application/json",Prefer:"return=representation"},body:JSON.stringify({order_number:orderNumber,customer_id:customer.id,subtotal:total,deposit_percentage:depositPct,deposit_amount:total*depositPct/100,remaining_amount:total-(total*depositPct/100),payment_method:data.payment_method,payment_status:"pending",order_status:"new",notes:data.notes||null,items})}); const orders=await orderResponse.json(); if(!orderResponse.ok)throw new Error(orders.message); state.cart=[];saveCart(); $("#checkoutContent").innerHTML=`<div class="success-panel"><b>✓</b><h2>${t("orderSuccess")}</h2><p>${t("orderNumber")}: <strong>${esc(orderNumber)}</strong></p></div>`; }catch(error){ console.error(error);toast(t("orderError"));button.disabled=false; } }
  document.addEventListener("click",event=>{ const category=event.target.closest("[data-category]"); if(category){state.category=category.dataset.category;renderCategories();renderProducts();} const add=event.target.closest("[data-add]"); if(add){event.stopPropagation();addToCart(add.dataset.add);} const product=event.target.closest("[data-product]"); if(product&&!event.target.closest("[data-add]"))showProduct(product.dataset.product); const qty=event.target.closest("[data-qty]"); if(qty){const row=state.cart.find(item=>String(item.id)===qty.dataset.qty);const p=state.products.find(item=>String(item.id)===qty.dataset.qty);if(row&&p){row.quantity=Math.max(0,Math.min(Number(p.stock_quantity),row.quantity+Number(qty.dataset.delta)));if(!row.quantity)state.cart=state.cart.filter(item=>item!==row);saveCart();}} const remove=event.target.closest("[data-remove]");if(remove){state.cart=state.cart.filter(item=>String(item.id)!==remove.dataset.remove);saveCart();} if(event.target.id==="checkoutButton")checkout(); if(event.target.closest("[data-close-dialog]"))$("#productDialog").close(); if(event.target.closest("[data-close-checkout]"))$("#checkoutDialog").close(); });
  $("#languageButton").addEventListener("click",()=>{state.lang=state.lang==="ar"?"en":"ar";localStorage.setItem("len-lang",state.lang);applyLanguage();}); $("#cartButton").addEventListener("click",()=>openCart()); $("#closeCart").addEventListener("click",()=>openCart(false)); $("#backdrop").addEventListener("click",()=>openCart(false)); $("#menuButton").addEventListener("click",()=>$("#mainNav").classList.toggle("open")); $("#searchButton").addEventListener("click",()=>{$("#shop").scrollIntoView();setTimeout(()=>$("#searchInput").focus(),300);}); $("#searchInput").addEventListener("input",event=>{state.query=event.target.value;renderProducts();}); document.addEventListener("submit",event=>{if(event.target.id==="checkoutForm"){event.preventDefault();submitOrder(event.target);}}); document.querySelectorAll("dialog").forEach(dialog=>dialog.addEventListener("click",event=>{if(event.target===dialog)dialog.close();}));
  applyLanguage(); load();
})();